# Project Information

site_name: CHN User Manual
site_url: https://uw-chn.github.io/CHN-User-Manual/
site_description: This is a description that ends up in the meta tag
site_author: Kelly Chang
copyright: null

repo_url: https://github.com/UW-CHN/CHN-User-Manual/
repo_name: "GitHub"
remote_branch: gh-pages
remote_name: origin

google_analytics: null

# Documentation Layout

nav:
  - HOME: index.md
  - SIEMENS PRISMA 3T:
    - Setting Up and Acquiring Scans: siemens-prisma/setting-up.md
    - "EPI: Basic Parameter and Sequence Issues": siemens-prisma/epi-basic.md
    - "EPI: Advanced Parameter and Sequence Issues": siemens-prisma/epi-advanced.md
    - "EPI: Artifacts": siemens-prisma/epi-artifacts.md
    - Miscellaneous: siemens-prisma/miscellaneous.md
  - PERIPHERALS:
    - BOLDscreen: peripherals/boldscreen.md
    - Button Boxes: peripherals/button-boxes.md
    - EyeLink 1000 Plus: peripherals/eyelink1000-plus.md
    - Mock Scanner: peripherals/mock-scanner.md
    - Sensimetrics S14: peripherals/sensimetrics-s14.md
    - Physiology: peripherals/physiology.md
  - FLYWHEEL:
    - General: flywheel/general.md
    - BIDS Curation: flywheel/bids-curation.md
    - FreeSurfer recon-all: flywheel/freesurfer-recon-all.md
  - APPENDIX:
    - Normal Operations Checklist: appendix/normal-checklist.md
    - Emergency Checklist: appendix/emergency-checklist.md
    - Forms: forms.md
    - Contact: contact.md

# Build Directories

theme:
  name: material
  navigation_depth: 3

docs_dir: 'docs'
site_dir: 'site'

extra_css:
  - css/custom.css

extra_javascript: []
extra_templates: []

# Formatting Options

markdown_extensions:
  - admonition
  - toc:
      permalink: True
      toc_depth: 2

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2
  - git-revision-date-localized