# Project Information

site_name: CHN User Manual
site_url: https://uw-chn.github.io/CHN-User-Manual/
site_description: This is a description that ends up in the meta tag
site_author: Center for Human Neuroscience

repo_name: "CHN User Manual"
repo_url: https://github.com/UW-CHN/CHN-User-Manual/

copyright: Copyright &copy; 2021 Center for Human Neuroscience

# Documentation Layout

nav:
  - HOME: index.md
  - SIEMENS PRISMA 3T:
    - Setting Up and Acquiring Scans: siemens-prisma/setting-up.md
    - "EPI: Basic Parameter and Sequence Issues": siemens-prisma/epi-basic.md
    - "EPI: Advanced Parameter and Sequence Issues": siemens-prisma/epi-advanced.md
    - "EPI: Artifacts": siemens-prisma/epi-artifacts.md
    - Miscellaneous: siemens-prisma/miscellaneous.md
  - PERIPHERALS:
    - BOLDscreen: peripherals/boldscreen.md
    - Button Boxes: peripherals/button-boxes.md
    - EyeLink 1000 Plus: peripherals/eyelink1000-plus.md
    - Mock Scanner: peripherals/mock-scanner.md
    - Sensimetrics S14: peripherals/sensimetrics-s14.md
    - Physiology: peripherals/physiology.md
  - COMPUTATIONAL RESOURCES:
    - computational-resources/computational-resources.md
    - Hyak: computational-resources/hyak.md
    - Cloud: computational-resources/cloud.md
    - IBIC: computational-resources/ibic.md
  - FLYWHEEL:
    - flywheel/flywheel.md
    - CMRR Physio: flywheel/cmrr-physio.md
    - MRIQC: flywheel/mriqc.md
    - BIDS Curation: flywheel/bids-curation.md
    - Exporting Data: flywheel/exporting-data.md
    - FreeSurfer recon-all: flywheel/freesurfer-recon-all.md
    - fMRIPrep: flywheel/fmriprep.md
    - qsiprep: flywheel/qsiprep.md
  - APPENDIX:
    - Normal Operations Checklist: appendix/normal-checklist.md
    - Emergency Checklist: appendix/emergency-checklist.md
    - Site Documentation: appendix/site-documentation.md
    - Contacts: appendix/contacts.md

# Build Directories

theme:
  name: material
  features:
    - navigation.indexes
  navigation_depth: 3

docs_dir: 'docs'
site_dir: 'site'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js
  - js/config.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/default.min.css
  - css/custom.css

extra_templates: []

# Formatting Options

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: True
      toc_depth: 3

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2
  - git-revision-date-localized